accounts/urls.py
from django.urls import include, path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('signin/', views.SigninView.as_view(), name='signin'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signout/', views.SignoutView.as_view(), name='signout'),
    path('ajaxlogin/', views.ajax_login, name='signin_ajax')
]

authajax/urls.py
from django.contrib import admin
from django.urls import include, path  #includeを追加
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required

# admin.site.login = login_required(admin.site.login)
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),  #追加
    path('web/', include('web.urls')),  #追加
    path('', RedirectView.as_view(url='/accounts')),
]

web/urls.py
from django.urls import path
from web import views

app_name = 'web'
urlpatterns = [
    path('article/', views.ArticleListView.as_view(), name='article_list'),
    path('article/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>/edit/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('article/create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    is_pro = models.BooleanField(
        default=False,
        help_text=_('Can access articles for pro / プロユーザ'),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        #abstract = True # ここを削除しないといけないことを忘れない！！！！！！！！！！

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'date_of_birth')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'date_of_birth',
                  'is_active', 'is_superuser', 'is_pro')

    def clean_password(self):
        return self.initial["password"]

accounts/views.py
from allauth.account import views
from allauth.account.forms import LoginForm
from django.shortcuts import HttpResponse, Http404, redirect
import json


class HomeView(views.TemplateView):
    template_name = 'accounts/home.html'


class SigninView(views.LoginView):
    template_name = 'accounts/signin.html'

    def dispatch(self, request, *args, **kwargs):
        response = super(SigninView, self).dispatch(request, *args, **kwargs)
        return response

    def form_valid(self, form):
        return super(SigninView, self).form_valid(form)


class SignupView(views.SignupView):
    template_name = 'accounts/signup.html'

    def get_context_data(self, **kwargs):
        context = super(SignupView, self).get_context_data(**kwargs)
        return context


class SignoutView(views.LogoutView):

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            self.logout()
        return redirect('/')


def ajax_login(request):
    if request.method == 'POST':
        # ログイン処理
        form = LoginForm(request.POST)
        if form.is_valid():
            status = "OK"
            form.login(request)
        else:
            status = "NG"
        # レスポンス形成
        res = {
            "status": status,
            "username": request.user.get_username(),
        }
        json_str = json.dumps(res, ensure_ascii=False, indent=2)
        response = HttpResponse(json_str, content_type='application/json; charset=UTF-8', status=None)
        return response
    else:
        raise Http404

accounts/templates/accounts/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- favicon -->
<!--    <link rel="shortcut icon" type="image/x-icon" href="/document/dogP5.gif">-->
    <!--bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!--ajax-->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/jquery-datetimepicker@2.5.20/jquery.datetimepicker.css">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">

        <div class="col-6">
          <h5>User Info</h5>
          <p id="user">LoginUser: {{request.user}}</p>
        </div>

        <div class="col-6">
          <h5>Auth</h5>
          <div>
            <a href="{% url 'accounts:home' %}">Home</a>
          </div>
          <div>
            <a href="{% url 'accounts:signout' %}">Log out</a>
          </div>
          <div>
            <a href="{% url 'accounts:signin' %}">Log in</a>
          </div>
          <div>
            <a href="{% url 'accounts:signup' %}">Sign up</a>
          </div>
          <div>
            <a href="/admin/">Admin</a>
          </div>
        </div>

        <div class="col-6">
          <h5>Article</h5>
          <div>
            <a href="{%url 'web:article_list' %}">Article List</a>
          </div>
          <div>
            <a href="{%url 'web:article_create' %}">Article Create</a>
          </div>
        </div>
      </div>

      <hr>
      <div class="row">
        {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }} alert-dismissible">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>{{ msg.tags }}</strong> {{msg}}
        </div>
        {% endfor %}
        {% endif %}
      </div>
      {% block body %}{% endblock %}
    </div>

    {% block script %}{% endblock %}
  </body>
</html>

accounts/templates/accounts/home.html
{% extends "accounts/base.html" %}
{% block title %}Home{% endblock %}

{% block body %}
{% endblock %}

{% block script %}
{% endblock %}

accounts/templates/accounts/signin.html
{% extends "accounts/base.html" %}
{% block title %}SignIn{% endblock %}

{% block body %}
<div>
  <form method="post" action="" id="signin_ajax">
    {% csrf_token %}
    {{form.as_p}}
    <button type="button" id="btn" class="button btn-primary">Sign In</button>
  </form>
</div>
{% endblock %}

{% block script %}
<!--Signin Ajax-->
<script type="text/javascript">
  $('#btn').click(function(event){
    var form = $('#signin_ajax');
    //console.log($('#testajax [name=post_type]').val())
    console.log(form.serializeArray())

    $.ajax({
      url: "{% url 'accounts:signin_ajax' %}",
      method: form.prop("method"),
      data: form.serialize(),
      timeout: 10000,
      dataType: "json",
    })
    .done( function(d) {
      window.alert(d.status)
      $('#user').text("LoginUser: "+d.username)
    })
  });
</script>
{% endblock %}

accounts/templates/accounts/signout.html
{% extends "accounts/base.html" %}
{% block title %}SignOut{% endblock %}

{% block body %}
{% endblock %}

{% block script %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}
{% block title %}SignUp{% endblock %}

{% block body %}
<div>
  <form method="post" action="{% url 'accounts:signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
    {% endif %}
    <button type="submit" class="btn-primary">Signup</button>
  </form>
</div>
{% endblock %}

{% block script %}
{% endblock %}