authajax/urls.py
from django.contrib import admin
from django.urls import include, path  #includeを追加
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required

# admin.site.login = login_required(admin.site.login)
admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),  #追加
    path('web/', include('web.urls')),  #追加
    path('', RedirectView.as_view(url='/accounts')),
]

web/urls.py
from django.urls import path
from web import views

app_name = 'web'
urlpatterns = [
    path('article/', views.ArticleListView.as_view(), name='article_list'),
    path('article/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>/edit/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('article/create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
]

web/templates/web/article_create.html
{% extends "accounts/base.html" %}
{% block title %}ArticleCreate{% endblock %}

{% block body %}
<form method="post">
  <table class="table">
    {{ form.as_table }}
  </table>
  <button class="btn btn-primary">Save</button>
  {% csrf_token %}
</form>
{% endblock %}

{% block script %}
{% endblock %}

web/templates/web/article_delete.html
{% extends "accounts/base.html" %}
{% block title %}ArticleDelete{% endblock %}

{% block body %}
<div class="row">
  <div class="col-12">
    <p>{{ object }} を削除していいですか?</p>
    <form method="post">
      <button class="btn btn-danger">削除する</button>
      {% csrf_token %}
    </form>
  </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

web/templates/web/article_detail.html
{% extends "accounts/base.html" %}
{% load rules %}
{% block title %}ArticleDetail{% endblock %}

{% block body %}
<form method="post">
  <table class="table">
    <tr>
      <th>PK</th>
      <td>{{object.pk}}</td>
    </tr>
    <tr>
      <th>Name</th>
      <td>{{object.name}}</td>
    </tr>
    <tr>
      <th>User</th>
      <td>{{object.created_by}}</td>
    </tr>
    <tr>
      <th>Category</th>
      <td>{{object.category |default:''}}</td>
    </tr>
    <tr>
      <th>Tags</th>
      <td>{%for tag in object.tags.all%}{{tag}},{%endfor%}</td>
    </tr>
    <tr>
      <th>For Pro</th>
      <td>{%if object.is_for_pro%}○{%endif%}</td>
    </tr>
  </table>
  {% has_perm 'web.rules_update_article' request.user object as is_editable %}
  {% if is_editable %}
  <a href="{% url 'web:article_update' pk=object.pk %}" class="btn btn-primary">Edit</a>
  <a href="{% url 'web:article_delete' pk=object.pk %}" class="btn btn-danger">Delete</a>
  {% endif %}
</form>
{% endblock %}

{% block script %}
{% endblock %}

web/templates/web/article_list.html
{% extends "accounts/base.html" %}
{% load rules %}

{% block title %}ArticleList{% endblock %}

{% block body %}
<div class="row">
  <table class="table">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created By</th>
      <th>Category</th>
      <th>Tags</th>
      <th>Pro</th>
    </tr>

    {% for article in object_list %}
    {% has_perm 'web.rules_read_article' request.user article as is_available %}
    <tr>
      <td>
        {% if is_available %}
        <button
            class="btn-primary"
            onclick=location.href="{% url 'web:article_detail' pk=article.pk %}">
          {{article.pk}}
        </button>
        {% else %}
        <button class="btn-default">{{article.pk}}</button>
        {% endif %}
      </td>
      <td>{{article.name}}</td>
      <td>{{article.created_by}}</td>
      <td>{{article.category |default:""}}</td>
      <td>{% for tag in article.tags.all %}{{tag}}, {%endfor%}</td>
      <td>{%if article.is_for_pro%}○{%endif%}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

{% block script %}
{% endblock %}

web/templates/web/article_update.html
{% extends "accounts/base.html" %}
{% block title %}ArticleUpdate{% endblock %}

{% block body %}
<form method="post">
  <table class="table">
    {{ form.as_table }}
  </table>
  <button class="btn btn-primary">Save</button>
  {% csrf_token %}
</form>
{% endblock %}

{% block script %}
{% endblock %}